# Generated by Django 3.2.6 on 2022-02-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('ramo', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(max_length=30, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/produtos')),
                ('quantidade', models.IntegerField(null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoriaproduto')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.fornecedor')),
            ],
        ),
    ]
